### ISSUE TITLE
Matplotlib returns an Exception when creating charts

### ISSUE THREAD

**Issue by alaudet** [alaudet/raspi-sump#11]
Sometimes under Python3 matplotlib returns an exceptions when trying to create charts.
Trying to reproduce the problem.

```
pi@raspberrypi:~/raspi-sump/csv $ rsumpwebchart.py

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/matplotlib/font_manager.py", line 1404, in <module>

    fontManager = pickle_load(_fmcache)

  File "/usr/lib/python3/dist-packages/matplotlib/font_manager.py", line 957, in pickle_load

    with open(filename, 'rb') as fh:

FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/.cache/matplotlib/fontList.py3k.cache'

 

During handling of the above exception, another exception occurred:

 

Traceback (most recent call last):

  File "/usr/local/bin/rsumpwebchart.py", line 11, in <module>

    from raspisump import webchart

  File "/usr/local/lib/python3.4/dist-packages/raspisump/webchart.py", line 13, in <module>

    from raspisump import todaychart

  File "/usr/local/lib/python3.4/dist-packages/raspisump/todaychart.py", line 14, in <module>

    import matplotlib.pyplot as plt

  File "/usr/lib/python3/dist-packages/matplotlib/pyplot.py", line 27, in <module>

    import matplotlib.colorbar

  File "/usr/lib/python3/dist-packages/matplotlib/colorbar.py", line 34, in <module>

    import matplotlib.collections as collections

  File "/usr/lib/python3/dist-packages/matplotlib/collections.py", line 27, in <module>

    import matplotlib.backend_bases as backend_bases

  File "/usr/lib/python3/dist-packages/matplotlib/backend_bases.py", line 56, in <module>

    import matplotlib.textpath as textpath

  File "/usr/lib/python3/dist-packages/matplotlib/textpath.py", line 19, in <module>

    import matplotlib.font_manager as font_manager

  File "/usr/lib/python3/dist-packages/matplotlib/font_manager.py", line 1412, in <module>

    _rebuild()

  File "/usr/lib/python3/dist-packages/matplotlib/font_manager.py", line 1397, in _rebuild

    fontManager = FontManager()

  File "/usr/lib/python3/dist-packages/matplotlib/font_manager.py", line 1056, in __init__

    self.afmlist = createFontList(self.afmfiles, fontext='afm')

  File "/usr/lib/python3/dist-packages/matplotlib/font_manager.py", line 567, in createFontList

    font = afm.AFM(fh)

  File "/usr/lib/python3/dist-packages/matplotlib/afm.py", line 346, in __init__

    parse_afm(fh)

  File "/usr/lib/python3/dist-packages/matplotlib/afm.py", line 335, in parse_afm

    doptional = _parse_optional(fh)

  File "/usr/lib/python3/dist-packages/matplotlib/afm.py", line 317, in _parse_optional

    d[key] = optional[key](fh)

  File "/usr/lib/python3/dist-packages/matplotlib/afm.py", line 281, in _parse_composites

    name, numParts = cc[1], _to_int(cc[2])

  File "/usr/lib/python3/dist-packages/matplotlib/afm.py", line 57, in _to_int

    return int(float(x))

ValueError: could not convert string to float: b'u'

 

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/matplotlib/font_manager.py", line 1404, in <module>

    fontManager = pickle_load(_fmcache)

  File "/usr/lib/python3/dist-packages/matplotlib/font_manager.py", line 957, in pickle_load

    with open(filename, 'rb') as fh:

FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/.cache/matplotlib/fontList.py3k.cache'

 

During handling of the above exception, another exception occurred:

 

Traceback (most recent call last):

  File "/usr/local/bin/rsumpwebchart.py", line 11, in <module>

    from raspisump import webchart

  File "/usr/local/lib/python3.4/dist-packages/raspisump/webchart.py", line 13, in <module>

    from raspisump import todaychart

  File "/usr/local/lib/python3.4/dist-packages/raspisump/todaychart.py", line 14, in <module>

    import matplotlib.pyplot as plt

  File "/usr/lib/python3/dist-packages/matplotlib/pyplot.py", line 27, in <module>

    import matplotlib.colorbar

  File "/usr/lib/python3/dist-packages/matplotlib/colorbar.py", line 34, in <module>

    import matplotlib.collections as collections

  File "/usr/lib/python3/dist-packages/matplotlib/collections.py", line 27, in <module>

    import matplotlib.backend_bases as backend_bases

  File "/usr/lib/python3/dist-packages/matplotlib/backend_bases.py", line 56, in <module>

    import matplotlib.textpath as textpath

  File "/usr/lib/python3/dist-packages/matplotlib/textpath.py", line 19, in <module>

    import matplotlib.font_manager as font_manager

  File "/usr/lib/python3/dist-packages/matplotlib/font_manager.py", line 1412, in <module>

    _rebuild()

  File "/usr/lib/python3/dist-packages/matplotlib/font_manager.py", line 1397, in _rebuild

    fontManager = FontManager()

  File "/usr/lib/python3/dist-packages/matplotlib/font_manager.py", line 1056, in __init__

    self.afmlist = createFontList(self.afmfiles, fontext='afm')

  File "/usr/lib/python3/dist-packages/matplotlib/font_manager.py", line 567, in createFontList

    font = afm.AFM(fh)

  File "/usr/lib/python3/dist-packages/matplotlib/afm.py", line 346, in __init__

    parse_afm(fh)

  File "/usr/lib/python3/dist-packages/matplotlib/afm.py", line 334, in parse_afm

    dcmetrics_ascii, dcmetrics_name = _parse_char_metrics(fh)

  File "/usr/lib/python3/dist-packages/matplotlib/afm.py", line 207, in _parse_char_metrics

    bbox = _to_list_of_floats(vals[3][2:])

  File "/usr/lib/python3/dist-packages/matplotlib/afm.py", line 73, in _to_list_of_floats

    return [_to_float(val) for val in s.split()]

  File "/usr/lib/python3/dist-packages/matplotlib/afm.py", line 73, in <listcomp>

    return [_to_float(val) for val in s.split()]

ValueError: could not convert string to float: b'72\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\

```
 

(Continues to repeats for many many lines and just ends)

**Comment by alaudet** [comment]
The user who reported this issue is also having an issue with the Python 2 version of Raspisump and matplotlib.  The user reported that there may have been corruption of the image when he did an update and reverting to an older image allows matplotlib to handle the fonts properly and create graphs.  I am going to keep this issue open as I will be getting a Pi3 and will do everything I can to reproduce the error.

**Comment by alaudet** [comment]
Have not been able to reproduce this error.  It may be a local issue to the user's pi.  Will reopen if anyone else experiences this.
